### ISSUE TITLE
Custom colors are not honored in graph previews

### ISSUE THREAD

**Issue by falzm** [facette/facette#195]
When creating graphs using custom-color series, the graph preview still uses the default color scheme.

**Comment by vbatoufflet** [comment]
This was fixed in fad6562c5a6d68cf4f357143ee470ee84975768e.

**Comment by falzm** [comment]
I reopen this issue because the bug persists with grouped series that have custom colors.

**Comment by vbatoufflet** [comment]
Indeed, there was an issue on how series options were merged. It should be fully addressed now.

See 2c863b13b940efb603c8b733646505cdbeacc68c.
